This is to solve #80 How can I add a form to collect attendee information
fossasia/support.eventyay.com pull request #120
Opened 2020-09-09 07:52 UTC by bellaphan

2020-09-10 17:26 UTC, snitin315 commented on event-setup/How-can-I-add-a-form-to-collect-attendee-information.md
> +Choose the event you want to creat the attendee form, then select, `event dashboard`.
```suggestion
Choose the event you want to create the attendee form, then select, `event dashboard`.
```

2020-09-11 10:19 UTC, bellaphan commented on event-setup/How-can-I-add-a-form-to-collect-attendee-information.md
> +Choose the event you want to creat the attendee form, then select, `event dashboard`.
Hello Nitin, I have deleted my repo to avoid the conflict, would it be possible for you to merge first then I will forked again. T.T

2020-09-11 11:06 UTC, snitin315 commented on event-setup/How-can-I-add-a-form-to-collect-attendee-information.md
> +Choose the event you want to creat the attendee form, then select, `event dashboard`.
Yes, It's possible.

2020-09-11 19:03 UTC, mariobehling requested changes

2020-09-12 16:16 UTC, bellaphan commented on event-setup/How-can-I-add-a-form-to-collect-attendee-information.md
> +![Collect attendee information](/images/Event-dashboard.png)
Can we have a name that we can use for log in page, manage event and event dashboard since most the of the functions on eventyay need to use these features

2020-09-13 14:32 UTC, closed without merging

2020-09-13 14:33 UTC, bellaphan commented
I will do this again