Create Article How to transfer the ownership of an event?
fossasia/support.eventyay.com pull request #124
Opened 2020-09-11 15:03 UTC by edenyay

this is to fix issue https://github.com/fossasia/support.eventyay.com/issues/71

2020-09-11 19:02 UTC, mariobehling requested changes

2020-09-11 19:02 UTC, mariobehling commented on event-roles/How-to-transfer-the-ownership-of-an-event.md
> +![Transfer ownership](/images/How-to-add-a-Twitter-account-feed-to-your-event-page-1.png)
Seems to be the wrong image and wrong name?

2020-09-12 07:13 UTC, edenyay commented on event-roles/How-to-transfer-the-ownership-of-an-event.md
> +![Transfer ownership](/images/How-to-add-a-Twitter-account-feed-to-your-event-page-1.png)
@mariobehling no, I used the same image as that step is the as in the other article. instead of uploading same image again.

2020-09-14 07:21 UTC, bellaphan commented
there are some conflicts I have to close and do again

2020-09-15 15:30 UTC, closed without merging