Add info about custom speaker and custom session form to page "How to add speakers and sessions settings, call for speakers and speakers form?" #97
fossasia/support.eventyay.com pull request #128
Opened 2020-09-14 08:49 UTC by bellaphan

2020-09-14 13:21 UTC, mariobehling requested changes

2020-09-14 13:21 UTC, mariobehling commented on event-setup/How-to-add-speakers-and-sessions-settings-call-for-speakers-and-speakers-form.md
>  ![Call for Speakers](/images/how-to-call-for-speakers3.png)
Please update name following naming convention along the lines "How to add speakers and sessions settings, call for speakers and speakers form"

2020-09-14 13:21 UTC, mariobehling commented on event-setup/How-to-add-speakers-and-sessions-settings-call-for-speakers-and-speakers-form.md
>  ![Call for Speakers](/images/how-to-call-for-speakers5.png)
Update name please

2020-09-14 13:21 UTC, mariobehling commented on event-setup/How-to-add-speakers-and-sessions-settings-call-for-speakers-and-speakers-form.md
>  ![Call for Speakers](/images/how-to-call-for-speakers6.png)
Update name please

2020-09-16 05:17 UTC, bellaphan commented
I have made the changes, I will close this and create a new PR

2020-09-16 05:17 UTC, closed without merging