This is to fix #159
fossasia/support.eventyay.com pull request #160
Opened 2020-09-28 10:18 UTC by bellaphan

2020-09-28 11:00 UTC, mariobehling requested changes

2020-09-28 11:00 UTC, mariobehling commented on event-setup/How-to-add-additional-information-such-as-event-type-links-refund-policy-terms-and-conditions-and-code-of-conduct.md
> +### 2. Select manage event
Should be ## instead of ###

2020-09-28 11:00 UTC, mariobehling commented on event-setup/How-to-add-additional-information-such-as-event-type-links-refund-policy-terms-and-conditions-and-code-of-conduct.md
>  ### 1. How to add event type?
Should be ## instead of ###

2020-09-28 11:00 UTC, mariobehling commented on event-setup/How-to-add-additional-information-such-as-event-type-links-refund-policy-terms-and-conditions-and-code-of-conduct.md
>  ### 2. How to add social media links?
Should be ## instead of ###

2020-09-28 11:00 UTC, mariobehling commented on event-setup/How-to-add-additional-information-such-as-event-type-links-refund-policy-terms-and-conditions-and-code-of-conduct.md
> +### 3. How to add refund policy?
Should be ## instead of ###

2020-09-28 11:00 UTC, mariobehling commented on event-setup/How-to-add-additional-information-such-as-event-type-links-refund-policy-terms-and-conditions-and-code-of-conduct.md
>  ### 4. How to add terms and conditions?
Should be ## instead of ###

2020-09-28 11:00 UTC, mariobehling commented on event-setup/How-to-add-additional-information-such-as-event-type-links-refund-policy-terms-and-conditions-and-code-of-conduct.md
>  ### 5. How to add code of conduct?
Should be ## instead of ###

2020-09-28 11:18 UTC, bellaphan commented
changes made

2020-09-28 15:15 UTC, mariobehling requested changes

2020-09-28 15:15 UTC, mariobehling commented on event-setup/How-to-add-additional-information-such-as-event-type-links-refund-policy-terms-and-conditions-and-code-of-conduct.md
> +## 1. How to add event type?
I still dont understand the numbering. Above it is 1., 2., 3. and then you start again with 1, 2, 3... and further below again? This kind of listing does not work.

2020-09-28 15:31 UTC, bellaphan commented
I have made changes from ##1 to ### a. (reduce the size of the subheading)

2020-09-30 09:23 UTC, mariobehling approved these changes

2020-09-30 09:23 UTC, merged